twig:
  default_path: '%kernel.project_dir%/templates'
  strict_variables: false
  globals:
    appConfig: '@App\Service\AppConfig'
    targetRepo: '@App\Repository\TargetRepository'
    sessionRepo: '@App\Repository\SessionRepository'
    authorRepo: '@App\Repository\AuthorRepository'
    obsRepo: '@App\Repository\ObservatoryRepository'
    docsRepo: '@App\Repository\DocRepository'
  form_themes:
    - 'form/fields.html.twig'