twig:
  default_path: '%kernel.project_dir%/templates'
  strict_variables: false
  globals:
    local_folder_base: '%env(LOCAL_FOLDER_BASE)%'
    google_maps_api_key: '%env(GOOGLE_MAPS_API_KEY)%'
    appConfig: '@App\Service\AppConfig'
    targetRepo: '@App\Repository\TargetRepository'
    sessionRepo: '@App\Repository\SessionRepository'
    authorRepo: '@App\Repository\AuthorRepository'
    obsRepo: '@App\Repository\ObservatoryRepository'
    docsRepo: '@App\Repository\DocRepository'
  form_themes:
    - 'form/fields.html.twig'